//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KON.DVBVMSMonitor {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KON.DVBVMSMonitor.properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        internal static string frmConfiguration_BaseTitle {
            get {
                return ResourceManager.GetString("frmConfiguration_BaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save ähnelt.
        /// </summary>
        internal static string frmConfiguration_btnSave_Text {
            get {
                return ResourceManager.GetString("frmConfiguration_btnSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string frmConfiguration_btnSave_Text_Disabled {
            get {
                return ResourceManager.GetString("frmConfiguration_btnSave_Text_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ForceBindEnabled ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyForceBindEnabled {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyForceBindEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die false ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyForceBindEnabled_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyForceBindEnabled_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ForceBindIPAddress ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyForceBindIPAddress {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyForceBindIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 127.0.0.1 ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyForceBindIPAddress_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyForceBindIPAddress_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ForceBindPathWithFilename ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyForceBindPathWithFilename {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyForceBindPathWithFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C:\Program Files\KON.DVBVMSMonitor\ForceBindIP64.exe ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyForceBindPathWithFilename_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyForceBindPathWithFilename_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LogLevel ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyLogLevel {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyLogLevel_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogLevel_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LogToConsole ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyLogToConsole {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogToConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die false ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyLogToConsole_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyLogToConsole_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TargetServiceCheckInterval ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServiceCheckInterval {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServiceCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10 ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServiceCheckInterval_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServiceCheckInterval_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TargetServiceName ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServiceName {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DVBVRecorder ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServiceName_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServiceName_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TargetServicePathWithFilename ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServicePathWithFilename {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServicePathWithFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C:\Program Files (x86)\DVBViewer\DVBVservice.exe ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServicePathWithFilename_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServicePathWithFilename_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TargetServiceProcessName ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServiceProcessName {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServiceProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DVBVservice ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServiceProcessName_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServiceProcessName_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TargetServiceStartDelay ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServiceStartDelay {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServiceStartDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0 ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServiceStartDelay_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServiceStartDelay_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TargetServiceTimeout ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServiceTimeout {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServiceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10 ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyTargetServiceTimeout_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyTargetServiceTimeout_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VerboseLogging ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyVerboseLogging {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyVerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die false ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyVerboseLogging_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyVerboseLogging_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebServiceEnabled ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyWebServiceEnabled {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die true ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyWebServiceEnabled_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceEnabled_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebServiceTimeout ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyWebServiceTimeout {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 5 ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyWebServiceTimeout_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceTimeout_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebServiceUrl ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyWebServiceUrl {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://localhost:8080/api/status2.html ähnelt.
        /// </summary>
        internal static string frmConfiguration_srsKeyWebServiceUrl_DefaultValue {
            get {
                return ResourceManager.GetString("frmConfiguration_srsKeyWebServiceUrl_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not executed with administrative permissions - expect untested misbehavior! ähnelt.
        /// </summary>
        internal static string Program_AdministratorRequired {
            get {
                return ResourceManager.GetString("Program_AdministratorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        internal static string Program_LogName {
            get {
                return ResourceManager.GetString("Program_LogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KON.DVBVMSMonitor ähnelt.
        /// </summary>
        internal static string Program_Name {
            get {
                return ResourceManager.GetString("Program_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Press enter to exit ... ähnelt.
        /// </summary>
        internal static string Program_RunAsConsole {
            get {
                return ResourceManager.GetString("Program_RunAsConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installing service at ähnelt.
        /// </summary>
        internal static string Service_Installing {
            get {
                return ResourceManager.GetString("Service_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstalling service at ähnelt.
        /// </summary>
        internal static string Service_Uninstalling {
            get {
                return ResourceManager.GetString("Service_Uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error un-/installing the service: ähnelt.
        /// </summary>
        internal static string Service_Uninstalling_Error {
            get {
                return ResourceManager.GetString("Service_Uninstalling_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service disable failed! ähnelt.
        /// </summary>
        internal static string TargetService_DisabledNotSuccessful {
            get {
                return ResourceManager.GetString("TargetService_DisabledNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service disable successful! ähnelt.
        /// </summary>
        internal static string TargetService_DisabledSuccessful {
            get {
                return ResourceManager.GetString("TargetService_DisabledSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service enable failed! ähnelt.
        /// </summary>
        internal static string TargetService_EnabledNotSuccessful {
            get {
                return ResourceManager.GetString("TargetService_EnabledNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service enable successful! ähnelt.
        /// </summary>
        internal static string TargetService_EnabledSuccessful {
            get {
                return ResourceManager.GetString("TargetService_EnabledSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process(es) kill failed! - (re)trying next cycle! ähnelt.
        /// </summary>
        internal static string TargetService_KilledNotSuccessful {
            get {
                return ResourceManager.GetString("TargetService_KilledNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process(es) kill successful! - Service stop successful! ähnelt.
        /// </summary>
        internal static string TargetService_KilledSuccessful {
            get {
                return ResourceManager.GetString("TargetService_KilledSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process(es) killing ... ähnelt.
        /// </summary>
        internal static string TargetService_Killing {
            get {
                return ResourceManager.GetString("TargetService_Killing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service restart failed! - (re)trying next cycle! ähnelt.
        /// </summary>
        internal static string TargetService_RestartedNotSuccessful {
            get {
                return ResourceManager.GetString("TargetService_RestartedNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service restart successful! ähnelt.
        /// </summary>
        internal static string TargetService_RestartedSuccessful {
            get {
                return ResourceManager.GetString("TargetService_RestartedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service start delayed! ähnelt.
        /// </summary>
        internal static string TargetService_StartDelayed {
            get {
                return ResourceManager.GetString("TargetService_StartDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service start failed! ähnelt.
        /// </summary>
        internal static string TargetService_StartedNotSuccessful {
            get {
                return ResourceManager.GetString("TargetService_StartedNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service start successful! ähnelt.
        /// </summary>
        internal static string TargetService_StartedSuccessful {
            get {
                return ResourceManager.GetString("TargetService_StartedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service starting ... ähnelt.
        /// </summary>
        internal static string TargetService_Starting {
            get {
                return ResourceManager.GetString("TargetService_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service stop failed! ähnelt.
        /// </summary>
        internal static string TargetService_StoppedNotSuccessful {
            get {
                return ResourceManager.GetString("TargetService_StoppedNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service stop successful! ähnelt.
        /// </summary>
        internal static string TargetService_StoppedSuccessful {
            get {
                return ResourceManager.GetString("TargetService_StoppedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service stopping ... ähnelt.
        /// </summary>
        internal static string TargetService_Stopping {
            get {
                return ResourceManager.GetString("TargetService_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HttpWebRequest Create successful! ähnelt.
        /// </summary>
        internal static string WebService_RequestCreated {
            get {
                return ResourceManager.GetString("WebService_RequestCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HttpWebRequest Dispose successful! ähnelt.
        /// </summary>
        internal static string WebService_RequestDisposed {
            get {
                return ResourceManager.GetString("WebService_RequestDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HttpWebRequest Time-Out! ähnelt.
        /// </summary>
        internal static string WebService_RequestTimedOut {
            get {
                return ResourceManager.GetString("WebService_RequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HttpWebResponse Create successful! ähnelt.
        /// </summary>
        internal static string WebService_ResponseCreated {
            get {
                return ResourceManager.GetString("WebService_ResponseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HttpWebResponse Dispose successful! ähnelt.
        /// </summary>
        internal static string WebService_ResponseDisposed {
            get {
                return ResourceManager.GetString("WebService_ResponseDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service restart not required! ähnelt.
        /// </summary>
        internal static string WebService_ServiceRestartNotRequired {
            get {
                return ResourceManager.GetString("WebService_ServiceRestartNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StatusCode was not HttpStatusCode.OK! ähnelt.
        /// </summary>
        internal static string WebService_StatusCodeNotOK {
            get {
                return ResourceManager.GetString("WebService_StatusCodeNotOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StatusCode was HttpStatusCode.OK! ähnelt.
        /// </summary>
        internal static string WebService_StatusCodeOK {
            get {
                return ResourceManager.GetString("WebService_StatusCodeOK", resourceCulture);
            }
        }
    }
}
